package com.shulalab.shula.theme

import androidx.compose.ui.graphics.Color

//generated by https://m3.material.io/theme-builder#/custom
//Color palette was taken here: https://colorhunt.co/palettes/popular

internal val md_theme_light_primary = Color(0xFFFF9668)
internal val md_theme_light_onPrimary = Color(0xFFF27D4A)
internal val md_theme_light_primaryContainer = Color(0xFFEFEFEF) //Light gray BG
internal val md_theme_light_onPrimaryContainer = Color(0xFF838282) //Text inside LGBG
internal val md_theme_light_secondary = Color(0xFFDBCAFF) //purple
internal val md_theme_light_onSecondary = Color(0xFFBD8FFF)
internal val md_theme_light_secondaryContainer = Color(0xFF6FF6FE)
internal val md_theme_light_onSecondaryContainer = Color(0xFF002022)
internal val md_theme_light_tertiary = Color(0xFF904D00)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFFFDCC2)
internal val md_theme_light_onTertiaryContainer = Color(0xFF2E1500)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color.White
internal val md_theme_light_onBackground = Color(0xFF221B00)
internal val md_theme_light_surface = Color(0xFFFFFBFF)
internal val md_theme_light_onSurface = Color(0xFF221B00)
internal val md_theme_light_surfaceVariant = Color(0xFFDBE4E7)
internal val md_theme_light_onSurfaceVariant = Color(0xFF3F484B)
internal val md_theme_light_outline = Color(0xFF70797B)
internal val md_theme_light_inverseOnSurface = Color(0xFFFFF0C0)
internal val md_theme_light_inverseSurface = Color(0xFF3A3000)
internal val md_theme_light_inversePrimary = Color(0xFF55D6F4)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF00687A)
internal val md_theme_light_outlineVariant = Color(0xFFBFC8CB)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = md_theme_light_primary
internal val md_theme_dark_onPrimary = md_theme_light_onPrimary
internal val md_theme_dark_primaryContainer = md_theme_light_primaryContainer
internal val md_theme_dark_onPrimaryContainer = md_theme_light_onPrimaryContainer
internal val md_theme_dark_secondary = md_theme_light_secondary
internal val md_theme_dark_onSecondary = md_theme_light_onSecondary
internal val md_theme_dark_secondaryContainer = md_theme_light_secondaryContainer
internal val md_theme_dark_onSecondaryContainer = md_theme_light_onSecondaryContainer
internal val md_theme_dark_tertiary = md_theme_light_tertiary
internal val md_theme_dark_onTertiary = md_theme_light_onTertiary
internal val md_theme_dark_tertiaryContainer = md_theme_light_tertiaryContainer
internal val md_theme_dark_onTertiaryContainer = md_theme_light_onTertiaryContainer
internal val md_theme_dark_error = md_theme_light_error
internal val md_theme_dark_errorContainer = md_theme_light_errorContainer
internal val md_theme_dark_onError = md_theme_light_onError
internal val md_theme_dark_onErrorContainer = md_theme_light_onErrorContainer
internal val md_theme_dark_background = md_theme_light_background
internal val md_theme_dark_onBackground = md_theme_light_onBackground
internal val md_theme_dark_surface = md_theme_light_surface
internal val md_theme_dark_onSurface = md_theme_light_onSurface
internal val md_theme_dark_surfaceVariant = md_theme_light_surfaceVariant
internal val md_theme_dark_onSurfaceVariant = md_theme_light_onSurfaceVariant
internal val md_theme_dark_outline = md_theme_light_outline
internal val md_theme_dark_inverseOnSurface = md_theme_light_inverseOnSurface
internal val md_theme_dark_inverseSurface = md_theme_light_inverseSurface
internal val md_theme_dark_inversePrimary = md_theme_light_inversePrimary
internal val md_theme_dark_shadow = md_theme_light_shadow
internal val md_theme_dark_surfaceTint = md_theme_light_surfaceTint
internal val md_theme_dark_outlineVariant = md_theme_light_outlineVariant
internal val md_theme_dark_scrim = md_theme_light_scrim


internal val seed = Color(0xFF2C3639)
